function isCaughtException(e) {
  return e instanceof CaughtException;
}